/* SPDX-License-Identifier: GPL-2.0 */

#ifndef DRIVERS_HAL_CIR_PLATFORM_CIR_SUN20IW1_H_
#define DRIVERS_HAL_CIR_PLATFORM_CIR_SUN20IW1_H_

#define SUNXI_IRADC_PBASE   0x07040000

#endif /* DRIVERS_HAL_CIR_PLATFORM_CIR_SUN20IW1_H_ */
