from building import *

objs = []
cwd  = GetCurrentDir()
src  = Glob('*.c')
list = os.listdir(cwd)
CPPPATH = [cwd]

#LCD
if GetDepend(['BSP_USING_LCD']):
	CPPPATH += [cwd + '/lcd']
	src += Split('''
		lcd/drv_lcd.c
		lcd/lcd_cfg.c
	''')

#USB HOST
if GetDepend(['T113_USING_USB0_HOST']) or GetDepend(['T113_USING_USB1_HOST']):
	CPPPATH += [cwd + '/usb']
	CPPPATH += [cwd + '/usb/ehci']
	#CPPPATH += [cwd + '/usb/ohci']
	src += Glob('usb/*.c')
	src += Glob('usb/ehci/*.c')
	#src += Glob('usb/ohci/*.c')

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group

Return('objs')
